apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eje-api
  labels:
    app: eje
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: eje.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eje-api
                port:
                  number: 80
  tls:
    - hosts:
        - eje.example.com
      secretName: eje-tls
